apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
            - name: MYSQL_DATABASE
              value: "hello_world_db"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
            # Removed subPath from the volumeMount to mount the entire ConfigMap
            - name: init-sql-config
              mountPath: /docker-entrypoint-initdb.d  # This will automatically include init.sql
      volumes:
        - name: mysql-storage
          emptyDir: {}
        - name: init-sql-config
          configMap:
            name: init-sql-config  # References the ConfigMap containing init.sql

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql

